"""empty message

Revision ID: 311846d52046
Revises: 9bcd90712880
Create Date: 2025-05-23 23:50:27.880013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311846d52046'
down_revision = '9bcd90712880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('conversations_last_message_id_fkey', type_='foreignkey')
        batch_op.drop_column('last_message_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('conversations_last_message_id_fkey', 'messages', ['last_message_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('preview')

    # ### end Alembic commands ###
